// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Product struct {
	ID        uuid.UUID
	Name      string
	Price     string
	CreatedAt sql.NullTime
}
